apiVersion: apps/v1
kind: Deployment
metadata:
  name: insider
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: insider
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: insider
        tier: backend
      annotations:
        version: v1.18
    spec:
      containers:
        - name: insider
          image: registry.cloud.okteto.net/insider-epicdog/insider:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_NAME
              value: Insider
            - name: APP_ENV
              value: qa
            - name: APP_KEY
              value: base64:WTjmcoJ/P0PH532caNGNkz6BWbC0KVE2ZfOyj9L4L9M=
            - name: LOG_CHANNEL
              value: daily
            - name: SIMULATION_DRIVER
              value: cache  
            - name: LOG_LEVEL
              value: debug
            - name: APP_URL
              value: https://web-insider-epicdog.cloud.okteto.net/
            - name: ASSET_URL
              value: https://web-insider-epicdog.cloud.okteto.net/
          volumeMounts:
          - name: storage-persistent-storage
            mountPath: /var/www/insider/storage
          lifecycle:
            postStart:
                exec:
                  command: 
                    - "/bin/sh"
                    - "-c"
                    - |
                    - php /var/www/insider/artisan view:clear;
                    - php /var/www/insider/artisan cache:clear;
      initContainers:
      - name: install
        imagePullPolicy: Always
        image: registry.cloud.okteto.net/insider-epicdog/insider:latest
        command: ["/bin/sh", "-c", "cp -R /var/www/insider/storage/. /var/www/insider/storage_target && chown -R www:www /var/www/insider/storage_target"]
        volumeMounts:
        - name: storage-persistent-storage
          mountPath: /var/www/insider/storage_target
      volumes:                       # A PersistentVolume is mounted as a volume to the Pod  
        - name: storage-persistent-storage
          persistentVolumeClaim:
            claimName: storage-pv-claim
